/**
 * Dados de demonstração do PaliVida.
 *
 * Espelham o app publicado: os 12 sintomas oficiais, os conteúdos educativos
 * completos (definição, sinais e sintomas, sinais de alerta — extraídos do
 * documento DEFINIÇÃO_FINALIZADO_280826) e os 3 usuários de teste (senha
 * "palivida123" para todos). Isso alimenta o "banco" em js/db.js.
 */
window.PALIVIDA_SEED = {
  sintomas: [
    'Constipação Intestinal',
    'Fraqueza',
    'Sonolência',
    'Tristeza (Depressão)',
    'Ansiedade',
    'Dor',
    'Náusea e Vômitos',
    'Dispneia (Falta de ar)',
    'Fadiga e Cansaço',
    'Xerostomia (Boca seca)',
    'Bem Estar',
    'Anorexia e Falta de apetite',
  ],

  conteudos: [
    {
      titulo: 'Constipação Intestinal',
      descricao: 'Caracterizado por evacuações com baixa frequência, podendo ser também incompletas e difíceis.',
      sinaissintomas: [
        'Dificuldade ou incapacidade de evacuar',
        'Necessidade de fazer muita força para evacuar',
        'Menos de três evacuações por semana',
        'Eliminação de fezes endurecidas',
        'Frequência de evacuação menor do que três vezes por semana',
        'Sensação de esvaziamento incompleto do reto',
      ].join('\n'),
      sinaisalerta: [
        'Sintomas de início rápido',
        'Náuseas ou vômito',
        'Dificuldade na eliminação de flatos',
        'Dor intensa',
        'Distensão abdominal (Barriga inchada ou estufada)',
        'Perda de peso sem explicação',
        'Sangramento pelo ânus',
        'Anemia ferropriva inexplicável',
        'História familiar de câncer de cólon',
      ].join('\n'),
    },
    {
      titulo: 'Fraqueza',
      descricao: 'É a dificuldade ou incapacidade de realizar movimentos em decorrência da diminuição ou perda da força muscular.',
      sinaissintomas: [
        'Dor',
        'Falta de ar',
        'Fadiga',
        'Perda do apetite',
        'Alterações neurológicas',
        'Perca de peso',
        'Formigamento',
      ].join('\n'),
      sinaisalerta: [
        'Fraqueza muscular intensa e redução da funcionalidade',
        'Sonolência a maior parte do tempo',
      ].join('\n'),
    },
    {
      titulo: 'Sonolência',
      descricao: 'Redução do nível de consciência, no qual há a possibilidade do indivíduo ser acordado por estímulos',
      sinaissintomas: [
        'Alteração de sono',
        'Desempenho ineficaz nos estudos',
        'Desempenho ineficaz no trabalho',
        'Esquecimentos',
        'Prejuízo e interferências no raciocínio',
        'Prejuízo e interferências na memória',
        'Alteração nas relações familiares',
        'Alteração nas relações sociais',
        'Dificuldade de fixar e manter a atenção',
        'Prejuízo na capacidade de planejamentos',
        'Alterações em atividades que envolvam agilidade e precisão',
        'Ineficaz controle de impulsos',
        'Fadiga/Cansaço',
        'Alterações gastrointestinais',
        'Alteração do humor',
        'Aumento do Estresse',
        'Depressão',
        'Prejuízo no aprendizagem',
        'Prejuízo na interação social',
        'Prejuízo na qualidade de vida',
      ].join('\n'),
      sinaisalerta: [
        'Abertura dos olhos com muita dificuldade e momentaneamente',
        'Sonolência prolongada',
        'Redução da resposta a estímulos verbais e visuais',
        'Delirium',
        'Torpor',
        'Coma',
      ].join('\n'),
    },
    {
      titulo: 'Tristeza (Depressão)',
      descricao: 'Variação de humor, marcada por tristeza, falta de motivação, ansiedade, sensação de vazio, falta de vontade, motivação e esperança.',
      sinaissintomas: [
        'Humor deprimido',
        'Perda do interesse ou do prazer em atividades diárias',
        'Alterações do sono (Dormindo muito ou pouco demais)',
        'Aumento ou diminuição do apetite',
        'Alteração de peso',
        'Mudança no interesse sexual',
        'Lentificação ou agitação psicomotora observada por outras pessoas (Ficar mais lento ou agitado demais)',
        'Fadiga (Aumento do cansaço)',
        'Perda de energia',
        'Falta de concentração',
        'Incapacidade de tomar decisões',
        'Pensamentos de culpa excessiva ou baixa autoestima.',
        'Pensamentos recorrentes de morte',
        'Ideação suicida (Pensamentos de se machucar ou de não querer mais viver)',
      ].join('\n'),
      sinaisalerta: [
        'Agitação',
        'Agressividade',
        'Alteração do Nível de Consciência',
        'Desorganização',
        'Ideação ou tentativa suicida (Risco imediato de a pessoa se machucar ou colocar sua segurança em perigo.)',
      ].join('\n'),
    },
    {
      titulo: 'Ansiedade',
      descricao: 'Mecanismo do organismo para nos avisar quando algo está errado ou com alteração. Caracterizado por tensão, hipervigilância e apreensão.',
      sinaissintomas: [
        'Preocupações excessivas',
        'Dificuldade em controlar a preocupação',
        'Dificuldade em relaxar',
        'Tensão muscular',
        'Sudorese (Suor excessivo)',
        'Sensação de falta de ar',
        'Taquipneia induzida (Aumento na respiração)',
        'Fadiga (Aumento do cansaço)',
        'Taquicardia (Coração batendo mais rápido que o normal)',
        'Hipertensão Arterial (Pressão alta)',
        'Desconforto torácico ou abdominal',
        'Dificuldade para dormir ou alterações no sono',
        'Aceleração na velocidade de fala',
        'Aceleração na velocidade do pensamento',
      ].join('\n'),
      sinaisalerta: [
        'Os sintomas não melhoram ou melhoram pouco mesmo com o tratamento;',
        'Associação ao uso abusivo, grave, de substâncias (medicamentos, álcool, drogas, entre outras)',
        'Ideação ou tentativa suicida (Risco imediato de a pessoa se machucar ou colocar sua segurança em perigo.)',
      ].join('\n'),
    },
    {
      titulo: 'Dor',
      descricao: 'É uma reação do sistema nervoso, de modo fisiológico a uma lesão tecidual, que pode ser estímulos mecânicos, químicos e térmicos.',
      sinaissintomas: [
        'Náuseas e Vômitos',
        'Sudorese (Suor excessivo)',
        'Taquicardia (Coração batendo mais rápido que o normal)',
        'Hipertensão Arterial (Pressão alta)',
        'Pele mais pálida que o habitual',
        'Alteração de tônus muscular (Músculos muito tensos ou muito relaxados)',
        'Dificuldade para dormir ou alterações no sono',
        'Ansiedade',
        'Irritabilidade',
        'Agitação',
        'Aumento ou diminuição do apetite',
        'Maior esforço ou dificuldade para respirar',
        'Aumento da frequência respiratória',
        'Lapso de consciência e de falta de atenção',
        'Sensação de queimação',
        'Sensação de peso',
        'Sensação de agulhadas e ferroadas',
        'Sensação de choques',
        'Sensação de formigamento ou adormecimento',
      ].join('\n'),
      sinaisalerta: [
        'Dor de difícil controle',
        'Dor de início súbito',
        'Incapacidade física, psicossocial e crônica',
        'Dor ou forte desconforto no peito',
        'Dor abdominal de inicio recente',
        'Alterações de humor e de comportamento',
      ].join('\n'),
    },
    {
      titulo: 'Náusea e Vômitos',
      descricao: 'Náusea é uma sensação subjetiva, caracterizada por mal-estar e incômodo que antecipa o vômito. Vômitos é eliminação forçada de conteúdo pela boca.',
      sinaissintomas: [
        'Anorexia (Falta ou perda de apetite de forma expressiva)',
        'Dor abdominal (Dor em região de barriga)',
        'Distensão abdominal (Barriga inchada ou estufada)',
        'Refluxo (Azia, queimação ou retorno do alimento/ácido para a boca)',
        'Constipação (Prisão de ventre)',
      ].join('\n'),
      sinaisalerta: [
        'Dor',
        'Febre',
        'Alteração da ingesta alimentar',
        'Perda de peso',
        'Cirurgias abdominais prévias',
        'Cefaleia (Dor de cabeça)',
        'Alterações visuais',
        'Vertigens (Tontura)',
        'Alterações neurológicas agudas',
        'Sinais de instabilidade hemodinâmica',
        'Desidratação',
      ].join('\n'),
    },
    {
      titulo: 'Dispneia (Falta de ar)',
      descricao: 'Sensação de desconforto ao respiratório, sentido como como falta de ar, desconforto em região de tórax, expiração incompleta ou aumento de esforço respiratório.',
      sinaissintomas: [
        'Ansiedade',
        'Depressão',
        'Alta emotividade',
        'Sensação de sufocação',
        'Tosse seca',
        'Tontura e desmaio',
        'Dor',
        'Pele mais pálida que o habitual',
        'Inchaço nas pernas e braços',
        'Exaustão',
        'Fraqueza generalizada',
        'Intolerância ao exercício',
        'Fraqueza muscular',
        'Dor ou forte desconforto no peito',
      ].join('\n'),
      sinaisalerta: [
        'Cianose (pele ou lábios azulados ou arroxeados)',
        'Dor torácica (Dor no peito)',
        'Secreções respiratórias audíveis ("sororoca")',
        'Confusão',
        'Falta de ar ao falar ou dificuldade para respirar, com sinais de cansaço ou exaustão;',
        'Respiração muito profunda, com suspiros frequentes, ou muito fraca, superficial e com pausas.',
      ].join('\n'),
    },
    {
      titulo: 'Fadiga e Cansaço',
      descricao: 'Sensação desagradável e subjetiva, que engloba cansaço a exaustão, desenvolvendo condição geral que interfere na capacidade funcional normal das pessoas.',
      sinaissintomas: [
        'Perda de massa muscular',
        'Falta de ar',
        'Anorexia',
        'Dor',
        'Náuseas e vômitos',
        'Depressão',
        'Ansiedade',
        'Dificuldade para dormir ou alterações no sono',
        'Alteração da autoestima',
        'Fraqueza corporal',
        'Sonolência',
        'Falta de disposição em atividades do cotidiano',
        'Lentidão de raciocínio',
        'Lentidão na concentração',
        'Lentidão de memória',
        'Alteração de humor',
        'Fraqueza corporal',
        'Interferência nas relações sociais',
      ].join('\n'),
      sinaisalerta: [
        'Piora na intensidade da fadiga/cansaço',
        'Redução do estado de atenção',
        'Inquietação ou sonolência excessiva, com pouca reação ou disposição.',
        'Palidez',
        'Alteração de Sinais Vitais',
      ].join('\n'),
    },
    {
      titulo: 'Xerostomia (Boca seca)',
      descricao: 'Sensação de boca seca, ocasionado devido a diminuição de produção das glândulas salivares ou por alteração de sua composição',
      sinaissintomas: [
        'Saliva mais espessa',
        'Falta de produção de saliva',
        'Alterações do paladar',
        'Sensação de queimação',
        'Capacidade de mastigação e deglutição alterada',
        'Dificuldades para falar',
        'Gengivite (Inflamação da gengiva)',
        'Rachaduras e ressecamentos de lábios',
        'Úlceras',
        'Dor na boca, face ou região da mandíbula.',
        'Língua dolorida, seca, de coloração vermelha',
        'Rouquidão',
        'Inflamação e halitose',
      ].join('\n'),
      sinaisalerta: [
        'Infecções',
        'Piora expressiva dos sinais e sintomas',
        'Incapacidade de se alimentar',
        'Ressecamento de mucosas e peles',
        'Ressecamento de aparelho respiratório, faringe, fossas nasais e garganta',
      ].join('\n'),
    },
    {
      titulo: 'Bem Estar',
      descricao: 'Percepção de modo positivo das suas condições de saúde',
      sinaissintomas: [
        'Dor',
        'Alteração de consciência',
        'Alteração no estado geral e saúde',
        'Conflito com suas crenças',
        'Cansaço/Fadiga',
        'Dificuldade nas atividades diárias e de locomoção',
        'Sono, ansiedade, tristeza',
        'Isolamento familiar/social',
        'Perda da autonomia e decisões',
        'Preocupações financeiras',
        'Falta de propósito',
        'Conflitos pessoais e familiares',
        'Ideação ou tentativa suicida (Risco imediato de a pessoa se machucar ou colocar sua segurança em perigo.)',
      ].join('\n'),
      sinaisalerta: [
        'Declínio importante do estado funcional, qualidade de vida, saúde mental e sentido da vida',
      ].join('\n'),
    },
    {
      titulo: 'Anorexia e Falta de apetite',
      descricao: 'Apresentada pela diminuição do apetite ou desejo de se alimentar',
      sinaissintomas: [
        'Perda de massa magra',
        'Perca de peso',
        'Fadiga',
        'Fraqueza',
        'Saciedade precoce',
        'Disfagia (dificuldade ou desconforto para engolir alimentos, líquidos ou saliva).',
        'Náusea',
        'Constipação(Prisão de ventre)',
        'Depressão',
        'Ansiedade',
        'Humor deprimido',
        'Alteração do olfato ou paladar',
        'Mucosites',
        'Estomatites',
        'Infecções',
        'Lesões em cavidade oral',
      ].join('\n'),
      sinaisalerta: [
        'Redução de ingesta',
        'Perda completa do apetite',
        'Perda de massa muscular e gordura em várias partes do corpo',
        'Parar de comer e diminui a aceitação de líquidos',
        'Perda da habilidade de engolir',
      ].join('\n'),
    },
  ],

  // senha "palivida123" para os três — texto puro só porque isto roda 100%
  // no navegador, sem servidor de verdade. Ver README do site.
  usuarios: {
    administrador: {
      nome: 'Administrador Demo',
      email: 'admin@palivida.local',
      senha: 'palivida123',
      formacao: 'Medicina',
      conselho_profissional: 'CRM',
    },
    paciente: {
      nome: 'Paciente Demo',
      email: 'paciente@palivida.local',
      senha: 'palivida123',
      cidade: 'Londrina',
      estado: 'PR',
      tipo_sanguineo: 'O+',
    },
    acompanhante: {
      nome_completo: 'Cuidador Demo',
      email: 'cuidador@palivida.local',
      senha: 'palivida123',
      relacionamento: 'filho(a)',
    },
  },

  // Registros iniciais (mesmas 4 primeiras "sintomas" x intensidades do seed original)
  registrosIniciais: [3, 7, 5, 9, 2, 6],
};
